### PR TITLE
fixed two bugs with wipe and route

### LINKED ISSUE #55: Unhandled exception on removing related app
### Bug Description

The traefik k8s operator throws an unhandled exception when a related app is removed.

### To Reproduce

1. Build and deploy traefik from current git main
2. Set and external hostname
3. Add a relation with an `IngressPerAppRequirer`
4. Remove the relation after it is established.

### Environment

Built and deployed from github on microk8s

### Relevant log output

```shell
unit-traefik-ingress-0: 10:20:19 ERROR unit.traefik-ingress/0.juju-log ingress:1: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 603, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/main.py", line 426, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/lib/charms/traefik_k8s/v0/ingress.py", line 250, in _handle_relation_broken
    self.on.data_removed.emit(event.relation)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 276, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 736, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 783, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 273, in _handle_ingress_data_removed
    self._wipe_ingress_for_relation(event.relation)
  File "./src/charm.py", line 498, in _wipe_ingress_for_relation
    if request := self.ingress_per_app.get_request(relation):
AttributeError: 'IngressPerAppProvider' object has no attribute 'get_request'
unit-traefik-ingress-0: 10:20:19 ERROR juju.worker.uniter.operation hook "ingress-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PietroPasotti**
## Issue
Fixed a bug in wipe codepath
Fixes #55 

## Release Notes
- Fixed bug (SDI leftover)

### CODE REVIEW

**Comment by PietroPasotti** [comment]
@balbirthomas if you want to take this branch for a test drive, woudl :)

**Comment by balbirthomas** [comment]
> @balbirthomas if you want to take this branch for a test drive, would be fantastic :)

Ack. Doing.

**Comment by balbirthomas** [comment]
I can confirm, removing relation does not throw and exception with fix in this PR.

**Review by balbirthomas — APPROVED** [review]

**Comment by PietroPasotti** [comment]
And some itests to verify that the relation removal paths are clean

**Review by jnsgruk — APPROVED** [review]

**Pull request merged**
